const tabs=['Overview','GA4','GSC','GBP','Heatmap','Support'];
const icons=['▦','▥','⌕','▣','⊞','?'];
const traffic=[['Organic Search',77,44,'57.14%','44s',5.08],['Direct',69,46,'66.67%','20s',6.04],['Organic Social',20,10,'50%','7s',4.20],['Paid Search',16,4,'25%','40s',3.19],['Paid Social',9,0,'0%','0s',3.00],['Referral',4,2,'50%','29s',13.50],['AI Assistant',1,1,'100%','36s',7.00]];
const users=[['Direct',66,63,3,'30s',.78],['Organic Search',52,50,14,'57s',.79],['Organic Social',19,19,1,'7s',.53],['Paid Social',9,9,0,'0s',0],['Paid Search',8,8,3,'1m 20s',.50],['Referral',3,3,0,'3s',.33],['AI Assistant',1,1,0,'36s',1]];
const landing=[['/',158,138,135,'32s',2],['/about-us',11,8,8,'17s',1],['(not set)',10,5,0,'0s',0],['/blow-in-insulation',6,3,3,'12s',1],['/privacy-policy',3,3,3,'4s',0],['/contact-us',2,1,1,'1s',0],['/batt-insulation',1,1,1,'13s',0],['/commercial-insulation',1,1,1,'0s',0],['/concrete-lifting',1,1,1,'20s',0],['/encapsulations',1,1,0,'45s',0]];
const tracked='/?utm_source=local&utm_medium=organic&utm_campaign=gbp_home';
const pages=[[tracked,35,2829],['/',17,559],['/about-us/',2,164],['/spray-foam-financing/',1,101],['/open-closed-cell-insulation/',0,158],['/contact-us/',0,151],['/crawl-space-insulation/',0,118],['/batt-insulation/',0,112],['/blow-in-insulation/',0,106],['/gallery/',0,68]];
const ai=[['/',35],['/about-us/',4],['/concrete-lifting/',2],['/contact-us/',2],[tracked,1],['/batt-insulation/',1],['/blow-in-insulation/',1],['/crawl-space-insulation/',1],['/gallery/',1],['/pole-barn-insulation/',1]];
const scopes=[['Core Reno','Downtown / Midtown / Core Reno','7 × 7 grid · 3–5 miles · Competitive niches'],['Reno–Sparks Metro','Greater Truckee Meadows / Reno–Sparks Metro','7 × 7 grid · 7–10 miles'],['Washoe County','Service-area business coverage','SAB · Washoe County']];
let current='Overview',gaView='Traffic acquisition',gscView='Pages',scope=0,cell=null,chartMetric='Sessions',insightView='Top',tableSort={col:1,asc:false};
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const metric=(label,value,note)=>`<article class="card metric"><div class="label">${label}</div><strong>${value}</strong><small>${note}</small></article>`;
const title=(heading,sub,badge='Aug 1–31, 2026')=>`<div class="section-title"><div><h2>${heading}</h2><p>${sub}</p></div><span class="badge">${badge}</span></div>`;
const business=()=>`<div class="business"><b>Spray Foam Giants</b><br>390 Freeport Blvd Ste 9<br>Sparks, NV 89431, United States<br><a href="tel:7753132453">775-313-2453</a></div>`;
function bars(rows,index=1){const max=Math.max(...rows.map(r=>r[index]));return `<div class="bars">${rows.map(r=>`<div class="bar-row"><span>${esc(r[0])}</span><button data-tip="${esc(r[0])}: ${r[index]} ${chartMetric.toLowerCase()}" aria-label="${esc(r[0])}: ${r[index]} ${chartMetric.toLowerCase()}" title="${esc(r[0])}: ${r[index]}"><div class="track"><div class="fill" style="width:${r[index]/max*100}%"></div></div></button><b>${r[index]}</b></div>`).join('')}</div>`}
function overview(){return title('Performance overview','Your website and search performance, in one place.')+`<div class="cards">${metric('Active users','156','GA4 · Website audience')}${metric('Sessions','196','GA4 · 107 engaged sessions')}${metric('Search clicks','54','GSC · Web search')}${metric('Search impressions','3.31K','GSC · As displayed in source')}</div><div class="layout"><section class="card"><div class="card-head"><div><h3>Where your traffic comes from</h3><p>Sessions by channel · GA4</p></div><span class="badge blue">196 sessions</span></div>${bars(traffic)}<div class="insight"><b>Organic Search leads acquisition.</b><br>77 sessions (39.29% of total), with a 57.14% engagement rate.</div></section><section class="card"><div class="card-head"><div><h3>Audience engagement</h3><p>Engaged sessions as a share of all sessions</p></div></div><div class="engagement"><div class="donut" role="img" aria-label="54.59 percent engagement rate, 107 of 196 sessions"><div><strong>54.59%</strong><small>engagement rate</small></div></div><div class="legend"><p><span class="dot"></span>107 engaged</p><p><span class="dot gray"></span>89 not engaged</p><small>Non-engaged count derived<br>from 196 − 107.</small></div></div><div class="status-row"><span>Avg. engagement / session</span><b>29s</b></div><div class="status-row"><span>New users</span><b>153</b></div><div class="status-row"><span>Key events</span><b>4</b></div><div class="status-row"><span>Recorded revenue</span><b>$0.00</b></div></section></div><div class="layout equal"><section class="card"><div class="card-head"><h3>Search visibility at a glance</h3><button data-nav="GSC">View GSC</button></div><div class="status-row"><span>Average click-through rate</span><b>1.6%</b></div><div class="status-row"><span>Average position</span><b>8.3</b></div><div class="status-row"><span>Generative AI impressions</span><b>42</b></div><p class="source-note">Search position is an aggregate GSC metric. It does not measure rankings at local grid coordinates.</p></section><section class="card"><h3>Reporting coverage</h3><div class="status-row"><div><b>Google Analytics 4</b><p>Acquisition, engagement and landing pages</p></div><span class="badge blue">Available</span></div><div class="status-row"><div><b>Google Search Console</b><p>Web search, pages and AI features</p></div><span class="badge blue">Available</span></div><div class="status-row"><div><b>Google Business Profile</b><p>Reporting data not provided</p></div><button data-nav="GBP">Unavailable</button></div><div class="status-row"><div><b>Local rank heatmap</b><p>Three coverage scopes prepared</p></div><button data-nav="Heatmap">View heatmap</button></div></section></div>`}
function table(headers,rows,note=''){return `<div class="table-wrap"><table><thead><tr>${headers.map((h,i)=>`<th><button data-sort="${i}" title="Sort by ${esc(h)}">${h}</button></th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="table-note">${note}</p>`}
function ga4(){const options=['Traffic acquisition','User acquisition','Landing pages','Sources'];let head,rows,note;if(gaView==='Traffic acquisition'){head=['Channel','Sessions','Engaged sessions','Engagement rate','Avg. engagement / session','Events / session'];rows=traffic;note='All 7 channels shown. Total: 196 sessions · 107 engaged · 54.59% engagement · 29s average engagement · 5.26 events/session.'}else if(gaView==='User acquisition'){head=['First user channel','Total users','New users','Returning users','Avg. engagement / active user','Engaged sessions / active user'];rows=users;note='Total: 158 total users · 153 new users · 21 returning users · 36s average engagement · 0.69 engaged sessions/active user. New and returning audiences can overlap.'}else if(gaView==='Landing pages'){head=['Landing page','Sessions','Active users','New users','Avg. engagement / session','Key events'];rows=landing;note='10 of 12 source rows visible. Total: 196 sessions · 156 active users · 153 new users · 29s average engagement · 4 key events · $0.00 revenue. All visible pages show $0.00 revenue; hidden rows are not invented.'}else{head=['Session manual source','Sessions'];rows=[['local',50],['google',37],['l.facebook.com',7],['facebook.com',6],['ig',5],['m.facebook.com',5],['fb',4]];note='Visible manual-source rows from Acquisition Overview. This is a partial source list, not a reconciliation of all 196 sessions.'}return title('Google Analytics 4','Audience, acquisition and engagement.')+`<div class="cards">${metric('Total users','158','156 active · 153 new')}${metric('Engaged sessions','107','54.59% engagement rate')}${metric('Avg. engagement','29s','Per session · 36s per active user')}${metric('Key events','4','Revenue recorded: $0.00')}</div><section class="card" style="margin-bottom:22px"><div class="card-head"><div><h3>Channel performance</h3><p>Monthly channel totals, transcribed from GA4</p></div><label class="muted">Chart metric <select id="chartMetric"><option ${chartMetric==='Sessions'?'selected':''}>Sessions</option><option ${chartMetric==='Engaged sessions'?'selected':''}>Engaged sessions</option></select></label></div>${bars(traffic,chartMetric==='Sessions'?1:2)}</section><section class="card"><div class="subcontrols">${options.map(o=>`<button data-ga="${o}" class="${gaView===o?'selected':''}">${o}</button>`).join('')}</div><div class="card-head"><h3>${gaView}</h3><input class="table-filter" type="search" aria-label="Filter GA4 table" placeholder="Filter table…"></div>${table(head,rows,note)}</section><p class="source-note">Daily chart points were not supplied as exact labeled values. This dashboard charts verified monthly totals instead of estimating a daily series. The realtime user card in the screenshot is excluded from the August report.</p>`}
function insights(){const topQ=[['spray foam giants',8,'−11%'],['blow in insulation',1,'Previously 0'],['home insulation',1,'Previously 0'],['insulation contractors',1,'Previously 0'],['insulation reno',1,'—']];const upQ=[['blow in insulation','+1','Previously 0'],['home insulation','+1','Previously 0'],['insulation contractors','+1','Previously 0'],['insulation services','+1','Previously 0'],['near me','+1','Previously 0']];const downQ=['attic insulation contractors near me','blown in insulation installation','commercial spray foam insulation contractors','insulation','insulation companies near me'].map(x=>[x,'−1','−100%']);const content=insightView==='Top'?[[tracked,31,'−9%'],['/',12,'−14%'],['/contact-us/',2,'Previously 0'],['/about-us/',1,'—'],['/service-area/',1,'Previously 0']]:insightView==='Trending up'?[['/contact-us/','+2','Previously 0'],['/service-area/','+1','Previously 0']]:[[tracked,'−3','−9%'],['/','−2','−14%'],['/spray-foam-financing/','−2','−100%']];return `<div class="notice"><b>Different reporting window: Last 28 days.</b> These Insights screenshots do not specify exact start/end dates. Their 46 clicks (−8%) and 3.34K impressions (+5%) are kept separate from the August totals.</div><div class="subcontrols">${['Top','Trending up','Trending down'].map(x=>`<button data-insight="${x}" class="${insightView===x?'selected':''}">${x}</button>`).join('')}</div><h3>Queries leading to your site</h3>${table(['Query',insightView==='Top'?'Clicks':'Click change','Comparison'],insightView==='Top'?topQ:insightView==='Trending up'?upQ:downQ,'Visible rows only · Last 28 days')}<h3 style="margin-top:28px">Your content</h3>${table(['Page',insightView==='Top'?'Clicks':'Click change','Comparison'],content,'Visible rows only · Last 28 days')}<h3 style="margin-top:28px">Top countries</h3>${table(['Country','Share of clicks'],[['United States','>99%'],['Argentina','<1%'],['Australia','<1%'],['Bangladesh','<1%'],['Brazil','<1%']],'Percentages retained exactly as displayed in Insights.')}`}
function gsc(){return title('Google Search Console','Web search visibility and generative AI features.')+`<div class="cards">${metric('Total clicks','54','Web search · August')}${metric('Total impressions','3.31K','Rounded display value from GSC')}${metric('Average CTR','1.6%','Click-through rate')}${metric('Average position','8.3','Aggregate search position')}</div><section class="card"><div class="subcontrols">${['Pages','Generative AI','Insights'].map(x=>`<button data-gsc="${x}" class="${gscView===x?'selected':''}">${x}</button>`).join('')}</div>${gscView==='Pages'?`<div class="card-head"><div><h3>Page performance</h3><p>Web search · August 1–31, 2026</p></div><input class="table-filter" type="search" aria-label="Filter GSC pages" placeholder="Filter pages…"></div>${table(['Page','Clicks','Impressions'],pages,'10 of 14 source rows visible. Values are preserved as shown; page-level totals need not reconcile with property-level totals.')}<div class="insight">The tagged home-page URL has <b>35 clicks and 2,829 impressions</b> in GSC. Its “gbp_home” campaign label does not substitute for a GBP performance report.</div>`:gscView==='Generative AI'?`<div class="card-head"><div><h3>Generative AI visibility</h3><p>GSC Generative AI features · August</p></div><span class="badge blue">42 total impressions</span></div><div class="layout equal"><div><h3>Impressions by country</h3>${table(['Country','Impressions'],[['United States',41],['Vietnam',1]])}</div><div class="insight" style="margin:0">Page impressions may overlap within the report. The total remains <b>42</b>; adding page rows is not a replacement for the reported total.<br><br>AI search impressions and GA4 AI Assistant sessions measure different activity.</div></div><h3>Pages appearing in AI features</h3>${table(['Page','Impressions'],ai,'10 of 12 source rows visible. No device breakdown or hidden rows are inferred.')}`:insights()}</section><p class="source-note">Source: supplied GSC screenshots. Main performance and AI charts show August dates. One original GSC attachment was not retrievable; exact August query, country and device tables unavailable in the recovered images are not reconstructed from Insights.</p>`}
function gbp(){return title('Google Business Profile','Business details and reporting availability.','Data unavailable')+`<section class="card empty"><div class="empty-icon" aria-hidden="true">▣</div><span class="badge">NOT PROVIDED</span><h2 style="margin-top:18px">GBP reporting data is unavailable</h2><p>No Google Business Profile performance dataset was supplied for August 2026. Calls, directions, profile views, website interactions and review metrics cannot be reported.</p><button data-nav="Support" class="primary">Request reporting support</button></section><div class="layout equal" style="margin-top:22px"><section class="card"><h3>Business information</h3>${business()}</section><section class="card"><h3>What is available elsewhere</h3><p class="muted">GA4 includes the manual source “local” with 50 sessions. GSC includes a URL tagged with the campaign “gbp_home”.</p><div class="insight">These are website analytics and search metrics. They are not GBP calls, views, direction requests or profile actions.</div></section></div>`}
function heatmap(){return title('Local visibility heatmap','Explore the planned scan scopes. All rank measurements are pending.','Awaiting rank data')+`<div class="heat-layout"><aside><section class="card"><h3>Coverage scope</h3><p class="muted" style="font-size:14px;margin-bottom:18px">Choose a service-market view.</p><div class="scope-list">${scopes.map((s,i)=>`<button data-scope="${i}" class="${scope===i?'selected':''}" aria-pressed="${scope===i}"><b>${s[0]}</b><small>${s[1]}<br>${s[2]}</small></button>`).join('')}</div></section><section class="card" style="margin-top:20px"><h3>Scan status</h3><div class="status-row"><span>Rank observations</span><b>Unavailable</b></div><div class="status-row"><span>Last scan</span><b>Not provided</b></div><p class="source-note">No local ranking data or scan coordinates were supplied. Grid locations will be assigned by a real scan.</p></section></aside><section class="card"><div class="card-head"><div><h3>${scopes[scope][0]}</h3><p>${scopes[scope][2]}</p></div><span class="badge">${scope===2?'Service area':'49 pending cells'}</span></div>${scope===2?`<div class="sab"><span class="eyebrow">SERVICE-AREA BUSINESS</span><h3>Washoe County</h3><p>Countywide service coverage requested.<br>Awaiting scan locations and rank data.</p><span class="badge">Coverage view · no measured rankings</span></div><p class="source-note">This is a service-area scope, not a verified service boundary or geographic rank map.</p>`:`<div class="grid-surface"><div class="compass">NORTH · PLANNED SCAN GRID</div><div class="rank-grid" aria-label="7 by 7 planned local rank grid">${Array.from({length:49},(_,i)=>`<button data-cell="${i}" class="${cell===i?'selected':''}" aria-label="Row ${Math.floor(i/7)+1}, column ${i%7+1}: awaiting scan data" title="Awaiting scan/data">—</button>`).join('')}</div><div class="rank-detail" aria-live="polite">${cell===null?'Select a cell to inspect its status.':`<b>Row ${Math.floor(cell/7)+1} · Column ${cell%7+1}</b><br>Rank: awaiting scan/data · Coordinate: not assigned`}</div></div><p class="source-note">Schematic 7×7 layout. The requested ${scope===0?'3–5':'7–10'} mile scope is retained as a range; no radius-versus-width assumption or geographic coordinates are fabricated.</p>`}<div class="insight"><b>Why every cell is pending</b><br>GA4 and GSC do not contain keyword rankings at each geographic coordinate. A local rank scan is needed to populate this view.</div></section></div>`}
function support(){return title('Support','Contact us about your report, website or local visibility.')+`<div class="layout"><section class="card"><h3>Contact support</h3><p class="source-note">Send a request to the support team. Include the relevant report section and any details that will help us investigate.</p><form id="supportForm"><input type="checkbox" name="botcheck" style="display:none" tabindex="-1" autocomplete="off" aria-hidden="true"><div class="form-grid"><label>Your name<input name="name" autocomplete="name" required></label><label>Email address<input name="email" type="email" autocomplete="email" required></label><label>Request type<select name="type"><option>Reporting question</option><option>Missing GBP data</option><option>Local rank scan</option><option>Website issue</option><option>Other</option></select></label><label>Priority<select name="priority"><option>Normal</option><option>Low</option><option>High</option><option>Urgent</option></select></label><label class="wide">Subject<input name="subject" required maxlength="160" placeholder="How can we help?"></label><label class="wide">Details<textarea name="details" required placeholder="Describe the question, issue, or data you need."></textarea></label><label>Related URL (optional)<input name="url" type="url" placeholder="https://"></label><label>Existing ticket reference (optional)<input name="reference" maxlength="100" placeholder="If you have one"></label><div class="wide"><button class="primary" type="submit">Submit request</button> <button class="secondary" type="reset">Reset form</button></div></div></form><p id="supportStatus" role="status" class="source-note"></p></section><aside><section class="card"><h3>Report guidance</h3><details open><summary>Where do these numbers come from?</summary><p>GA4 and GSC screenshots supplied for this report. Rounded values and partial table coverage are identified. No live analytics connection is configured.</p></details><details><summary>How do I add GBP reporting?</summary><p>Provide the August 1–31, 2026 Google Business Profile performance export or screenshots. Include the report period and metric labels.</p></details><details><summary>What does the heatmap need?</summary><p>A genuine local rank scan with keyword, scan date, coordinates, grid scope and rank/status for each point. GA4 and GSC cannot fill these fields.</p></details><details><summary>How does Export PDF work?</summary><p>It opens the browser print dialog with all report sections. Choose Save as PDF to save the report. Support form contents are excluded.</p></details></section><section class="card" style="margin-top:22px"><h3>Business on this report</h3>${business()}</section></aside></div>`}
function content(t){return ({Overview:overview,GA4:ga4,GSC:gsc,GBP:gbp,Heatmap:heatmap,Support:support})[t]()}
function render(){ $('#tabs').innerHTML=tabs.map((t,i)=>`<button data-nav="${t}" class="${current===t?'active':''}" aria-current="${current===t?'page':'false'}"><span aria-hidden="true">${icons[i]}</span>${t}</button>`).join('');$('#app').innerHTML=content(current);}
function navigate(t){if(!tabs.includes(t))throw Error('Unknown dashboard tab');current=t;render();}
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').style.display='none',4500)}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.nav)navigate(b.dataset.nav);if(b.dataset.tip)toast(b.dataset.tip);if(b.dataset.ga){gaView=b.dataset.ga;render()}if(b.dataset.gsc){gscView=b.dataset.gsc;render()}if(b.dataset.insight){insightView=b.dataset.insight;render()}if(b.dataset.scope!==undefined){scope=Number(b.dataset.scope);cell=null;render()}if(b.dataset.cell!==undefined){cell=Number(b.dataset.cell);render();document.querySelector(`[data-cell="${cell}"]`).focus()}if(b.dataset.sort!==undefined){const i=Number(b.dataset.sort),tbody=b.closest('table').tBodies[0];tableSort={col:i,asc:tableSort.col===i?!tableSort.asc:true};const rows=[...tbody.rows];rows.sort((a,c)=>{let x=a.cells[i].textContent,y=c.cells[i].textContent;let comparison=typeof x==='string'&&/^-?[\d,.]+%?$/.test(x)&&/^-?[\d,.]+%?$/.test(y)?parseFloat(x.replaceAll(',',''))-parseFloat(y.replaceAll(',','')):x.localeCompare(y);return tableSort.asc?comparison:-comparison});rows.forEach(r=>tbody.appendChild(r));b.closest('tr').querySelectorAll('th').forEach(th=>th.removeAttribute('aria-sort'));b.closest('th').setAttribute('aria-sort',tableSort.asc?'ascending':'descending')}});
document.addEventListener('input',e=>{if(e.target.matches('.table-filter')){const term=e.target.value.toLowerCase();e.target.closest('section').querySelectorAll('tbody tr').forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(term))}});
document.addEventListener('change',e=>{if(e.target.id==='chartMetric'){chartMetric=e.target.value;render()}if(e.target.id==='period'){$('#periodNote').hidden=e.target.value!=='other';if(e.target.value==='other'){$('#app').hidden=true;$('#export').disabled=true}else{$('#app').hidden=false;$('#export').disabled=false}}});
$('#restore').onclick=()=>{$('#period').value='aug';$('#periodNote').hidden=true;$('#app').hidden=false;$('#export').disabled=false};
document.addEventListener('submit',async e=>{
  if(e.target.id!=='supportForm')return;
  e.preventDefault();
  const form=e.target,status=form.parentElement.querySelector('#supportStatus'),key=window.WEB3FORMS_ACCESS_KEY;
  if(!key||key==='YOUR_WEB3FORMS_ACCESS_KEY_HERE'){status.textContent='Support form setup is pending. Please contact your support representative directly.';return;}
  const data=new FormData(form);if(data.get('botcheck'))return;
  const button=form.querySelector('[type="submit"]');if(button.disabled)return;
  button.disabled=true;button.textContent='Sending…';status.textContent='Sending your request…';
  data.set('access_key',key);data.set('from_name','Spray Foam Giants Dashboard');data.set('reporting_period','August 1–31, 2026');
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);
  try{
    const response=await fetch('https://api.web3forms.com/submit',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(Object.fromEntries(data)),signal:controller.signal});
    const result=await response.json();
    if(!response.ok||result.success!==true)throw new Error('Submission failed');
    status.textContent='Your request was sent successfully. Thank you for contacting support.';form.reset();
  }catch(error){status.textContent=error.name==='AbortError'?'The request timed out. Delivery could not be confirmed. Please check with support before sending again.':'Your request could not be confirmed. Your details are still here; please try again or contact support directly.';}
  finally{clearTimeout(timer);button.disabled=false;button.textContent='Submit request';}
});
let printing=false;function preparePrint(){if(printing)return;printing=true;const saved=[gaView,gscView,scope,insightView,chartMetric,cell];let html=overview();for(const v of ['Traffic acquisition','User acquisition','Landing pages','Sources']){gaView=v;html+=`<section class="print-section">${ga4()}</section>`}for(const v of ['Pages','Generative AI','Insights']){gscView=v;html+=`<section class="print-section">${gsc()}</section>`}html+=`<section class="print-section">${gbp()}</section>`;for(let i=0;i<3;i++){scope=i;cell=null;html+=`<section class="print-section">${heatmap()}</section>`}[gaView,gscView,scope,insightView,chartMetric,cell]=saved;const report=document.createElement('div');report.id='printReport';report.className='print-only';report.innerHTML=html;$('#app').classList.add('no-print');$('#app').after(report)}
function restorePrint(){document.getElementById('printReport')?.remove();$('#app').classList.remove('no-print');printing=false}
$('#export').onclick=()=>{preparePrint();window.print()};window.addEventListener('beforeprint',preparePrint);window.addEventListener('afterprint',restorePrint);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'navigate_dashboard',description:'Open a Spray Foam Giants dashboard tab.',inputSchema:{type:'object',properties:{tab:{type:'string',enum:tabs}},required:['tab'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!tabs.includes(input.tab))throw Error('Invalid tab');navigate(input.tab);return {tab:current,period:'2026-08-01/2026-08-31'}}})).catch(()=>{})}catch{}}
render();
